version: '3'

services:
  db:
    container_name: db_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - 5432:5432
    volumes:
      - db_directory:/var/lib/postgresql/data
  api:
    restart: always
    depends_on:
      - db
    build: .
    links:
      - db
    ports:
      - 8000:8000

volumes:
  data:
    db_directory: local
